export default [
    { id: "CAB", nombre: "Capital Federal" },
    { id: "BSA", nombre: "Buenos Aires" },
    { id: "CAT", nombre: "Catamarca" },
    { id: "COR", nombre: "Córdoba" },
    { id: "CRR", nombre: "Corrientes" },
    { id: "CHA", nombre: "Chaco" },
    { id: "CHU", nombre: "Chubut" },
    { id: "ENT", nombre: "Entre Ríos" },
    { id: "FOR", nombre: "Formosa" },
    { id: "JUJ", nombre: "Jujuy" },
    { id: "PAM", nombre: "La Pampa" },
    { id: "RIO", nombre: "La Rioja" },
    { id: "MEN", nombre: "Mendoza" },
    { id: "MIS", nombre: "Misiones" },
    { id: "NEU", nombre: "Neuquén" },
    { id: "RNE", nombre: "Río Negro" },
    { id: "SAL", nombre: "Salta" },
    { id: "SJU", nombre: "San Juan" },
    { id: "SLU", nombre: "San Luis" },
    { id: "SCR", nombre: "Santa Cruz" },
    { id: "SFE", nombre: "Santa Fe" },
    { id: "SDE", nombre: "Santiago del Estero" },
    { id: "TDF", nombre: "Tierra del Fuego" },
    { id: "TUC", nombre: "Tucumán" },
]